### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.aruco.Aruco.getPredefinedDictionary_0(int)

### ISSUE THREAD

**Issue by luliang-ll** [RivoLink/Aruco-Android#3]
**Hello,

I'm also trying to use Android to detect A r U co. recently and I found your code and I think it's very good. But in the process of running it, I found this problem. I have searched google but no one seems to have the same problem. Do you have any solution for this, please?**

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.cameracalibration, PID: 14744
    java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.aruco.Aruco.getPredefinedDictionary_0(int) (tried Java_org_opencv_aruco_Aruco_getPredefinedDictionary_10 and Java_org_opencv_aruco_Aruco_getPredefinedDictionary_10__I)
        at org.opencv.aruco.Aruco.getPredefinedDictionary_0(Native Method)
        at org.opencv.aruco.Aruco.getPredefinedDictionary(Aruco.java:105)
        at com.example.cameracalibration.calibration.CameraCalibrator.<init>(CameraCalibrator.java:64)
        at com.example.cameracalibration.calibration.CameraCalibrationActivity.onCameraViewStarted(CameraCalibrationActivity.java:174)
        at org.opencv.android.CameraBridgeViewBase.processEnterState(CameraBridgeViewBase.java:323)
        at org.opencv.android.CameraBridgeViewBase.checkCurrentState(CameraBridgeViewBase.java:313)
        at org.opencv.android.CameraBridgeViewBase.surfaceChanged(CameraBridgeViewBase.java:198)
        at android.view.SurfaceView.updateSurface(SurfaceView.java:770)
        at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:155)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2746)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1722)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7605)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
        at android.view.Choreographer.doCallbacks(Choreographer.java:852)
        at android.view.Choreographer.doFrame(Choreographer.java:787)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1014)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Any help I would greatly appreciate.**

**Comment by RivoLink** [comment]
Hi, sorry for my late

**Comment by RivoLink** [comment]
Hi, sorry for my late

I don't know if you found the solution but I past this link here: 
https://github.com/RivoLink/opencv-android/tree/master/opencv3_4_4_contrib/native/libs

You can try to add these libs in this directory of the project:
https://github.com/RivoLink/Aruco-Android/tree/master/opencv344-contrib/src/main/jniLibs

Tell me if that doesn't help you.

**Comment by luliang-ll** [comment]
Thank you very much for your reply! When I posted this issue, I realized that my problem was the same situation as the first issue. So I solved the problem based on your answer in there. After that, I closed the issue but forgot to tell you that my problem was solved.

You are really nice! Thanks again.

**Comment by RivoLink** [comment]
You're welcome :) 

I'm happy that the project can help you.
